name: sixam_mart
description: A Multi-vendor Food. Grocery, eCommerce, Pharmacy & Parcel service.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  carousel_slider: ^4.0.0
  connectivity: ^3.0.6
  country_code_picker: ^2.0.2
  firebase_core: ^1.2.1
  firebase_messaging: ^11.2.4
  flutter:
    sdk: flutter
  flutter_html: ^2.2.1
  flutter_inappwebview: ^5.4.3+7
  flutter_local_notifications: ^9.5.3+1
  flutter_localizations:
    sdk: flutter
  flutter_typeahead: ^4.0.0
  flutter_widget_from_html: ^0.8.5
  font_awesome_flutter: ^10.1.0
  fwfh_selectable_text: ^0.8.3+1
  geolocator: ^8.0.1
  get: ^4.6.5
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.1.5
  google_maps_flutter_web: ^0.3.2
  http: ^0.13.4
  image_compression_flutter: ^1.0.2
  image_picker: ^0.8.4+11
  path_provider: ^2.0.8
  phone_number: ^0.12.0+1
  photo_view: ^0.14.0
  pin_code_fields: ^7.3.0
  pointer_interceptor: ^0.9.0+1
  shared_preferences: ^2.0.11
  shimmer_animation: ^2.1.0+1
  universal_html: ^2.0.8
  universal_ui: ^0.0.8
  url_launcher: ^6.1.2
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400

        - asset: assets/font/Poppins-Medium.ttf
          weight: 500

        - asset: assets/font/Poppins-Bold.ttf
          weight: 700

        - asset: assets/font/Poppins-Black.ttf
          weight: 900

    - family: Outfit
      fonts:

        - asset: assets/font/Outfit-Black.ttf
          weight: 900

        - asset: assets/font/Outfit-Bold.ttf
          weight: 700

        - asset: assets/font/Outfit-Regular.ttf
          weight: 400

        - asset: assets/font/Outfit-Medium.ttf
          weight: 500
        # - asset: assets/font/Roboto-Regular.ttf
        #   weight: 400
        # - asset: assets/font/Roboto-Medium.ttf
        #   weight: 500
        # - asset: assets/font/Roboto-Bold.ttf
        #   weight: 700
        # - asset: assets/font/Roboto-Black.ttf
        #   weight: 900
